# Generated by Django 4.0.2 on 2022-04-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spots',
        ),
    ]
