# Generated by Django 4.0.2 on 2022-04-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Семе', 'Семе'), ('Луковица', 'Луковица'), ('Разсад', 'Разсад'), ('Плод', 'Плод')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Домат', 'Домат'), ('Краставица', 'Краставица'), ('Лук', 'Лук')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='plants',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plants',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.kind'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.type'),
        ),
    ]
