# Generated by Django 4.0.2 on 2022-04-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_kind_type_plants_name_alter_plants_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
