# Generated by Django 4.0.2 on 2022-04-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_places_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='craft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='web.craft'),
            preserve_default=False,
        ),
    ]
