# Generated by Django 4.0.2 on 2022-04-10 12:41

import django.core.validators
from django.db import migrations, models
import motherearth.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_plants_kind_alter_plants_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), motherearth.common.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
