# Generated by Django 4.0.2 on 2022-04-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_category_places_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
