# Generated by Django 4.0.2 on 2022-04-10 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_plants_name_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
