# Generated by Django 4.0.2 on 2022-04-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('Западно Северняшко', 'Западно Северняшко'), ('Лудогорие', 'Лудогорие'), ('Добруджа', 'Добруджа'), ('Шоплук', 'Шоплук'), ('Тракия', 'Тракия'), ('Македония', 'Македония'), ('Родопа', 'Родопа'), ('Странджа', 'Странджа')], max_length=20),
        ),
    ]
